name: Run tests
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container: jjerphan/numba_dpex_dev:latest
      # options: --device=/dev/dri  # enable gpu passthrough

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sklearn-numba-dpex
      run: pip install -e . --no-build-isolation

    - name: Check device
      run: python -c "import dpctl; dpctl.select_default_device().print_device_info()"

    - name: Install pytest
      run: pip install pytest

    - name: Run tests
      run: pytest sklearn_numba_dpex/
